allowBuilds:
  "@clerk/shared": true
  "@prisma/engines": true
  bufferutil: true
  core-js: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - "@types/node@25.9.1"
  - "@types/react@19.2.15"
  - postcss@8.5.15
  - styled-components@6.4.2
onlyBuiltDependencies:
  - "@clerk/shared"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - core-js
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
